name: dinetrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  supabase_flutter: ^2.0.0
  go_router: ^12.0.0
  provider: ^6.1.1
  http: ^1.1.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.0
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android: true
  ios: true
  color_dark: "#000000"
  image_dark: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/logo.png
